pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://jitpack.io")
            content {
                includeGroup("com.github.DeweyReed")
                includeModule("com.github.PhilJay", "MPAndroidChart")
                includeModule("com.github.kizitonwose", "CalendarView")
                includeModule("com.github.zawadz88", "MaterialPopupMenu")
                includeModule("com.github.Carbs0126", "NumberPickerView")
                includeModule("com.github.ultimate-deej", "twowaynestedscrollview")
                includeModule("com.github.cardinalby", "accurate-count-down-timer")
            }
        }
    }
}

rootProject.name = "TimerMachine"

include(":domain")
include(":data")
include(":presentation")
include(":app-base")
include(":component-key")
include(":component-settings")
include(":component-tts")
include(":app-scheduler")
include(":app-settings")
include(":app-backup")
include(":app-tasker")
include(":app-timer-run")
include(":app-timer-edit")
include(":app-timer-list")
include(":app-timer-one")
include(":component-main")
include(":app-analytics-fake")
include(":flavor-google")
include(":app-intro")
include(":app")
include(":baselineprofile")
