plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.hilt)
}

android {
    namespace 'xyz.aprildown.timer.app.backup'
    buildFeatures {
        compose true
    }
}

dependencies {
    implementation project(':app-base')
    implementation project(':component-key')

    testImplementation libs.junit
    testImplementation libs.kotlin.coroutines.test
    testImplementation libs.bundles.mockito.core

    implementation libs.androidx.preference
    implementation libs.androidx.documentFile

    implementation platform(libs.compose.bom)
    implementation libs.bundles.compose

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    implementation libs.okio
    implementation libs.permission

}
