name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Android
        uses: ./.github/actions/android-setup

      - name: Build with Gradle
        run: ./gradlew app:assembleDogDebug
